package view.products;

import java.io.IOException;
import java.net.URL;
import java.util.ResourceBundle;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import javafx.scene.Parent;
import javafx.scene.input.MouseEvent;

import javafx.scene.layout.BorderPane;

public class ProductsController{
	@FXML
	private BorderPane productsBorderpane;

	
	// Event Listener on Button.onMouseClicked
	@FXML
	public void productsList(MouseEvent event) {
		loadContent("ProductsList");
	}
	// Event Listener on Button.onMouseClicked
	@FXML
	public void productsAdd(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onMouseClicked
	@FXML
	public void productsEdit(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onMouseClicked
	@FXML
	public void productsDelete(MouseEvent event) {
		// TODO Autogenerated
	}
	
	private void loadContent(String ui) {
		Parent content = null;
		try {
			content = FXMLLoader.load(getClass().getResource(ui+".fxml"));
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		productsBorderpane.setCenter(content);
	}
	
}
