package view.foodDiary;

import java.io.IOException;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.input.MouseEvent;

import javafx.scene.layout.BorderPane;

public class FoodDiaryController {
	@FXML
	private BorderPane foodDiaryBorderpane;

	// Event Listener on Button.onMouseClicked
	@FXML
	public void foodDiaryList(MouseEvent event) {
		loadContent("FoodDiaryList");
	}
	// Event Listener on Button.onMouseClicked
	@FXML
	public void foodDiaryAdd(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onMouseClicked
	@FXML
	public void foodDiaryEdit(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onMouseClicked
	@FXML
	public void foodDiaryDelete(MouseEvent event) {
		// TODO Autogenerated
	}
	
	private void loadContent(String ui) {
		Parent content = null;
		try {
			content = FXMLLoader.load(getClass().getResource(ui+".fxml"));
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		foodDiaryBorderpane.setCenter(content);
	}
}
