package view.fridge;

import java.io.IOException;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.input.MouseEvent;

import javafx.scene.layout.BorderPane;

public class FridgeController {
	@FXML
	private BorderPane fridgeBorderpane;

	// Event Listener on Button.onMouseClicked
	@FXML
	public void fridgeList(MouseEvent event) {
		loadContent("FridgeList");
	}
	// Event Listener on Button.onMouseClicked
	@FXML
	public void fridgeAdd(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onMouseClicked
	@FXML
	public void fridgeEdit(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onMouseClicked
	@FXML
	public void fridgeDelete(MouseEvent event) {
		// TODO Autogenerated
	}
	
	private void loadContent(String ui) {
		Parent content = null;
		try {
			content = FXMLLoader.load(getClass().getResource(ui+".fxml"));
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		fridgeBorderpane.setCenter(content);
	}
}
